float:
  any:
  - base_args: ['@metric']
    constructor: MiniOBVector
    disabled: false
    docker_tag: ann-benchmarks-miniob
    module: ann_benchmarks.algorithms.miniob
    name: miniob
    run_groups:
      base:
        arg_groups: [{unix_socket: "/home/miniob/miniob_test/players/data/miniob.sock"}]
        args: {}
        query_args: [[1]]